# Generated by Django 6.1.1 on 2026-09-23 05:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimPayout',
            fields=[
                ('id_payout', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_siniestro', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('pse', 'PSE'), ('transferencia', 'Transferencia')], default='transferencia', max_length=20)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
            ],
            options={
                'db_table': 'claim_payouts',
                'indexes': [models.Index(fields=['id_siniestro'], name='idx_claim_payouts_siniestro')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_payout_amount_positivo'), models.CheckConstraint(condition=models.Q(('status__in', ['pendiente', 'pagado', 'fallido'])), name='chk_payout_status')],
            },
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id_pago', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_poliza', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('pse', 'PSE'), ('transferencia', 'Transferencia')], max_length=20)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
            ],
            options={
                'db_table': 'premium_payments',
                'indexes': [models.Index(fields=['id_poliza'], name='idx_premium_payments_poliza'), models.Index(fields=['due_date'], name='idx_premium_payments_due_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_premium_amount_positivo'), models.CheckConstraint(condition=models.Q(('method__in', ['tarjeta', 'pse', 'transferencia'])), name='chk_premium_method'), models.CheckConstraint(condition=models.Q(('status__in', ['pendiente', 'pagado', 'fallido'])), name='chk_premium_status')],
            },
        ),
    ]
